run_dir: ./runs/test_mcunet
manual_seed: 0
evaluate: false
ray_tune: 0
resume: 0

data_provider:
  dataset: image_folder
  root: ../synthetic_dataset
  resize_scale: 0.08
  color_aug: 0.4
  base_batch_size: 32
  n_worker: 4
  image_size: 128
  num_classes: 2

run_config:
  n_epochs: 3
  base_lr: 0.01
  bs256_lr: null
  warmup_epochs: 1
  warmup_lr: 0
  lr_schedule_name: cosine
  weight_decay: 0
  no_wd_keys: ['norm', 'bias']
  optimizer_name: sgd
  bias_only: 0
  fc_only: 0
  fc_lr10: 0
  eval_per_epochs: 1
  grid_output: null
  grid_ckpt_path: null
  n_block_update: -1

net_config:
  net_name: mcunet-5fps
  pretrained: false
  cls_head: linear
  dropout: 0.
  mcu_head_type: fp

backward_config:
  enable_backward_config: 0
  n_bias_update: null
  n_weight_update: null
  weight_update_ratio: null
  weight_select_criteria: magnitude+
  pw1_weight_only: 0
  manual_weight_idx: null
  quantize_gradient: 0
  freeze_fc: 0
  train_scale: 0